### ISSUE TITLE
Spring does not send to Logstash

### ISSUE THREAD

**Issue by JohnatanT** [piomin/spring-boot-logging#9]
Hi, I really liked your library first.

I verified that the Spring application is showing the log in and out of requests, however they are not arriving in logstash. I did some tests and saw that everything is normal in Logtstash, could you tell me all the necessary settings?

I saw the blog post but I didn't find it very clear.

Thanks.

**Comment by JohnatanT** [comment]
My application.properties:

spring.logstash.url=localhost:5000
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
pl.piomin.logging.config.SpringLoggingAutoConfiguration



My logstash.conf:

input {
  tcp {
    port => 5000
    codec => json
  }
}

output {
  elasticsearch { hosts => ["localhost:9200"] }
  stdout { codec => rubydebug }
}

**Comment by piomin** [comment]
Hi. The library has been changed a little since I writing the article. First, following Spring Boot quideline I changed the property names from spring.logstash.* to logging.logstash.*, so you should use `logging.logstash.url` instead of `spring.logastash.url`. You also don't have to place ```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=
pl.piomin.logging.config.SpringLoggingAutoConfiguration
``` - it wasn't required since the beginning. You just have to include it. But the more significant change related to logging is that you have to set the property `logging.logstash.enabled` to `true` in order to enable default auto-configuration to logstash. Without it library tries to load your logstash configuration available inside logstash.xml.
